apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clixx-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/deejaydhiz/clixx-k8s-gitops.git
    targetRevision: main
    path: argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

