apiVersion: v1
kind: Service
metadata:
  name: clixx-service
  namespace: default
spec:
  selector:
    app: clixx-web-app
  ports:
    - port: 80           # Service port exposed to LB
      targetPort: 80     # Pod port
      protocol: TCP

