apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels: 
    app: nginx
    new_serv: clixx_serv_1
spec:
  selector:
    app: nginx #this matches the pods to deploy the service to
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

